dev:
  catalog_name: dev
  schema_name: restaurant_forecasting
prd:
  catalog_name: prd
  schema_name: restaurant_forecasting

experiment_name_basic: /Shared/restaurant-forecasting-basic

target: visitors

num_features:
  - latitude
  - longitude
  - month
  - holiday_flg
  - weekend_flg
  - visitors_last_day
  - visitors_mean_roll_7

cat_features:
  - dow
  - store_genre
  - area

parameters:
  learning_rate: 0.05
  n_estimators: 500
  max_depth: 6